# docker-compose.override.yml
services:
  api:
    command: sh -c "/usr/sbin/crond -f -l 8 & npm run dev"
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./api/crontab:/var/spool/cron/crontabs/root:ro

  frontend:
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
